local me,ns=...
local lang=GetLocale()
local l=LibStub("AceLocale-3.0")
local L=l:NewLocale(me,"enUS",true,true)
L["%1$d%% lower than %2$d%%. Lower %s"] = true
L["%s for a wowhead link popup"] = true
L["%s start the mission without even opening the mission page. No question asked"] = true
L["%s starts missions"] = true
L["%s to actually start mission"] = true
L["%s to blacklist"] = true
L["%s to remove from blacklist"] = true
L[ [=[%s, please review the tutorial
(Click the icon to dismiss this message and start the tutorial)]=] ] = true
L["%s, please review the tutorial\\n(Click the icon to dismiss this message)"] = true
L["Allow to start a mission directly from the mission list page (no single mission page shown)"] = true
L["Always counter increased resource cost"] = true
L["Always counter increased time"] = true
L["Always counter kill troops (ignored if we can only use troops with just 1 durability left)"] = true
L["Always counter no bonus loot threat"] = true
L["Artifact shown value is the base value without considering knowledge multiplier"] = true
L["Attempting %s"] = true
L["Base Chance"] = true
L["Better parties available in next future"] = true
L["Blacklisted"] = true
L["Blacklisted missions are ignored in Mission Control"] = true
L["Bonus Chance"] = true
L["Building Final report"] = true
L["but using troops with just one durability left"] = true
L["Capped %1$s. Spend at least %2$d of them"] = true
L["Changes the sort order of missions in Mission panel"] = true
L["Combat ally is proposed for missions so you can consider unassigning him"] = true
L["Complete all missions without confirmation"] = true
L["Configuration for mission party builder"] = true
L["Cost reduced"] = true
L["Could not fulfill mission, aborting"] = true
L["Counter kill Troops"] = true
L["Customization options (non mission related)"] = true
L["Disables warning: "] = true
L["Dont use this slot"] = true
L["Don't use troops"] = true
L["Duration reduced"] = true
L["Duration Time"] = true
L["Elite: Prefer overcap"] = true
L["Elites mission mode"] = true
L["Empty missions sorted as last"] = true
L["Empty or 0% success mission are sorted as last. Does not apply to \"original\" method"] = true
L["Equipped by following champions:"] = true
L["Expiration Time"] = true
L["Favours leveling follower for xp missions"] = true
L["For elite missions, tries hard to not go under 100% even at cost of overcapping"] = true
L["General"] = true
L["Global approx. xp reward"] = true
L["Global approx. xp reward per hour"] = true
L["HallComander Quick Mission Completion"] = true
L["If %1$s is lower than this, then we try to achieve at least %2$s without going over 100%%. Ignored for elite missions."] = true
L["If not checked, inactive followers are used as last chance"] = true
L[ [=[If you %s, you will lose them
Click on %s to abort]=] ] = true
L["Ignore busy followers"] = true
L["Ignore inactive followers"] = true
L["Keep cost low"] = true
L["Keep extra bonus"] = true
L["Keep time short"] = true
L["Keep time VERY short"] = true
L[ [=[Launch the first filled mission with at least one locked follower.
Keep %s pressed to actually launch, a simple click will only print mission name with its followers list]=] ] = true
L[ [=[Launch the first filled mission with at least one locked follower.
Keep SHIFT pressed to actually launch, a simple click will only print mission name with its followers list]=] ] = true
L["Level"] = true
L["Lock all"] = true
L["Lock this follower"] = true
L["Locked follower are only used in this mission"] = true
L["Make Order Hall Mission Panel movable"] = true
L["Makes sure that no troops will be killed"] = true
L["Max champions"] = true
L["Maximize xp gain"] = true
L["Mission duration reduced"] = true
L["Mission was capped due to total chance less than"] = true
L["Missions"] = true
L["Never kill Troops"] = true
L["No follower gained xp"] = true
L["No suitable missions. Have you reserved at least one follower?"] = true
L["Not blacklisted"] = true
L["Nothing to report"] = true
L["Notifies you when you have troops ready to be collected"] = true
L["Only accept missions with time improved"] = true
L["Only consider elite missions"] = true
L["Only need %s instead of %s to start a mission from mission list"] = true
L["Only use champions even if troops are available"] = true
L["Open configuration"] = true
--[[Translation missing --]]
L[ [=[OrderHallCommander overrides GarrisonCommander for Order Hall Management.
 You can revert to GarrisonCommander simply disabling OrderhallCommander.
If instead you like OrderHallCommander remember to add it to Curse client and keep it updated]=] ] = ""
L["Original method"] = true
L["Position is not saved on logout"] = true
L["Prefer high durability"] = true
L["Quick start first mission"] = true
L["Remove no champions warning"] = true
L["Restart tutorial from beginning"] = true
L["Resume tutorial"] = true
L["Resurrect troops effect"] = true
L["Reward type"] = true
L["Sets all switches to a very permissive setup. Very similar to 1.4.4"] = true
L["Show tutorial"] = true
L["Show/hide OrderHallCommander mission menu"] = true
L["Sort missions by:"] = true
L["Started with "] = true
L["Success Chance"] = true
L["Troop ready alert"] = true
L["Unable to fill missions, raise \"%s\""] = true
L["Unable to fill missions. Check your switches"] = true
L["Unable to start mission, aborting"] = true
L["Unlock all"] = true
L["Unlock this follower"] = true
L["Unlocks all follower and slots at once"] = true
L["Unsafe mission start"] = true
L["Upgrading to |cff00ff00%d|r"] = true
L["URL Copy"] = true
L["Use at most this many champions"] = true
L["Use combat ally"] = true
L["Use this slot"] = true
L["Uses troops with the highest durability instead of the ones with the lowest"] = true
L["When no free followers are available shows empty follower"] = true
L["When we cant achieve the requested %1$s, we try to reach at least this one without (if possible) going over 100%%"] = true
L["Would start with "] = true
L["You are wasting |cffff0000%d|cffffd200 point(s)!!!"] = true
L[ [=[You need to close and restart World of Warcraft in order to update this version of OrderHallCommander.
Simply reloading UI is not enough]=] ] = true
L["You now need to press both %s and %s to start mission"] = true

L=l:NewLocale(me,"zhCN")
if (L) then
L["%1$d%% lower than %2$d%%. Lower %s"] = "%1$d%%低于%2$d%%，降低%s"
L["%s for a wowhead link popup"] = true
L["%s start the mission without even opening the mission page. No question asked"] = "Shift-点击可以不打开任务页面就启动任务。没有问题"
L["%s starts missions"] = true
L["%s to actually start mission"] = true
L["%s to blacklist"] = "点击右键加入黑名单"
L["%s to remove from blacklist"] = "点击右键从黑名单中删除"
L[ [=[%s, please review the tutorial
(Click the icon to dismiss this message and start the tutorial)]=] ] = true
L["%s, please review the tutorial\\n(Click the icon to dismiss this message)"] = "%s，请检查教程\\n（单击图标取消此消息）"
L["Allow to start a mission directly from the mission list page (no single mission page shown)"] = true
L["Always counter increased resource cost"] = "总是反制增加资源花费"
L["Always counter increased time"] = "总是反制增加任务时间"
L["Always counter kill troops (ignored if we can only use troops with just 1 durability left)"] = "总是反制杀死部队(如果我们用只剩一次耐久的部队则忽略)"
L["Always counter no bonus loot threat"] = "总是反制没有额外奖励的威胁"
L["Artifact shown value is the base value without considering knowledge multiplier"] = "神器显示的值是基础值，没有经过神器知识的加成"
L["Attempting %s"] = "尝试%s"
L["Base Chance"] = "基础机率"
L["Better parties available in next future"] = "在将来有更好的队伍"
L["Blacklisted"] = "加入黑名单"
L["Blacklisted missions are ignored in Mission Control"] = "加入黑名单的任务将会在任务面板被忽略"
L["Bonus Chance"] = "额外奖励机率"
L["Building Final report"] = "构建最终报告"
L["but using troops with just one durability left"] = "使用只有一个生命值的部队"
L["Capped %1$s. Spend at least %2$d of them"] = "%1$s封顶了。花费至少%2$d在它身上"
L["Changes the sort order of missions in Mission panel"] = "改变任务面板上的任务排列顺序"
L["Combat ally is proposed for missions so you can consider unassigning him"] = "战斗盟友被建议到任务，所以你可以考虑取消指派他"
L["Complete all missions without confirmation"] = "完成所有任务不须确认"
L["Configuration for mission party builder"] = "任务队伍构建设置"
L["Cost reduced"] = "已降低花费"
L["Could not fulfill mission, aborting"] = "任务无法执行被忽略"
L["Counter kill Troops"] = "反制危害（致命）防止部队阵亡"
L["Customization options (non mission related)"] = true
L["Disables warning: "] = "停用警告："
L["Dont use this slot"] = "不要使用这个空位"
L["Don't use troops"] = "不要使用部队"
L["Duration reduced"] = "持续时间已缩短"
L["Duration Time"] = "持续时间"
L["Elite: Prefer overcap"] = true
L["Elites mission mode"] = "精英任务模式"
L["Empty missions sorted as last"] = "空的任务排在最后"
L["Empty or 0% success mission are sorted as last. Does not apply to \"original\" method"] = "空或者0%成功率的任务排在最后，对于\\\"原始\\\"方式排序无效。"
L["Equipped by following champions:"] = true
L["Expiration Time"] = "到期时间"
L["Favours leveling follower for xp missions"] = "倾向于使用升级中追隨者在经验值任务"
L["For elite missions, tries hard to not go under 100% even at cost of overcapping"] = true
L["General"] = "一般"
L["Global approx. xp reward"] = "整体大约经验值奖励"
L["Global approx. xp reward per hour"] = "每小时获得的整体经验值奖励"
L["HallComander Quick Mission Completion"] = "大厅指挥官快速任务完成"
L["If %1$s is lower than this, then we try to achieve at least %2$s without going over 100%%. Ignored for elite missions."] = "如果 %1$s 低于此值，那么我们至少尝试达到 %2$s 而不超过100%%。 忽略精英任务。"
L["If not checked, inactive followers are used as last chance"] = "不勾选时，未激活的追随者会成为最后的考虑"
L[ [=[If you %s, you will lose them
Click on %s to abort]=] ] = [=[如果你继续，你会失去它们
点击%s來取消]=]
L["Ignore busy followers"] = "忽略任务中的追随者"
L["Ignore inactive followers"] = "忽略未激活的追随者"
L["Keep cost low"] = "节省大厅资源"
L["Keep extra bonus"] = "优先额外奖励"
L["Keep time short"] = "减少任务时间"
L["Keep time VERY short"] = "最短任务时间"
L[ [=[Launch the first filled mission with at least one locked follower.
Keep %s pressed to actually launch, a simple click will only print mission name with its followers list]=] ] = true
L[ [=[Launch the first filled mission with at least one locked follower.
Keep SHIFT pressed to actually launch, a simple click will only print mission name with its followers list]=] ] = true
L["Level"] = "等级"
L["Lock all"] = "全部锁定"
L["Lock this follower"] = "锁定此追随者"
L["Locked follower are only used in this mission"] = "锁定只用于此任务的追随者"
L["Make Order Hall Mission Panel movable"] = "让大厅任务面板可移动"
L["Makes sure that no troops will be killed"] = "确保没有部队会阵亡"
L["Max champions"] = "最多的勇士数量"
L["Maximize xp gain"] = "获取最多的经验"
L["Mission duration reduced"] = "任务执行时间已缩短"
L["Mission was capped due to total chance less than"] = "任务限制由于总的几率少于"
L["Missions"] = "任务"
L["Never kill Troops"] = "确保部队绝不阵亡"
L["No follower gained xp"] = "没有追随者获得经验"
L["No suitable missions. Have you reserved at least one follower?"] = "没有合适的任务。 您是否至少保留了一位追随者？"
L["Not blacklisted"] = "未加入黑名单"
L["Nothing to report"] = "没什么可报告"
L["Notifies you when you have troops ready to be collected"] = "当部队已准备好获取时提醒你"
L["Only accept missions with time improved"] = "只允许有时间改善的任务"
L["Only consider elite missions"] = "只考虑精英任务"
L["Only need %s instead of %s to start a mission from mission list"] = true
L["Only use champions even if troops are available"] = "有可用的部队时，仍然只使用追随者"
L["Open configuration"] = "打开配置"
L[ [=[OrderHallCommander overrides GarrisonCommander for Order Hall Management.
 You can revert to GarrisonCommander simply disabling OrderhallCommander.
If instead you like OrderHallCommander remember to add it to Curse client and keep it updated]=] ] = true
L["Original method"] = "原始方法"
L["Position is not saved on logout"] = "位置不会在登出后储存"
L["Prefer high durability"] = "喜欢高生命值"
L["Quick start first mission"] = "快速开始第一个任务"
L["Remove no champions warning"] = "取消没有追随者警告"
L["Restart tutorial from beginning"] = true
L["Resume tutorial"] = true
L["Resurrect troops effect"] = "复活部队效果"
L["Reward type"] = "奖励类型"
L["Sets all switches to a very permissive setup. Very similar to 1.4.4"] = true
L["Show tutorial"] = "显示教程"
L["Show/hide OrderHallCommander mission menu"] = "显示/隐藏大厅指挥官任务选单"
L["Sort missions by:"] = "排列任务根据："
L["Started with "] = "开始"
L["Success Chance"] = "成功机率"
L["Troop ready alert"] = "部队装备提醒"
L["Unable to fill missions, raise \"%s\""] = "无法指派任务，请提升 \\\"%s\\"
L["Unable to fill missions. Check your switches"] = "无法指派任务，请检查您的设定选项"
L["Unable to start mission, aborting"] = "无法开始任务，中止"
L["Unlock all"] = "全部解除锁定"
L["Unlock this follower"] = "解锁此追随者"
L["Unlocks all follower and slots at once"] = "一次性解锁所有追随者和空位"
L["Unsafe mission start"] = true
L["Upgrading to |cff00ff00%d|r"] = "升级到|cff00ff00%d|r"
L["URL Copy"] = "复制网址"
L["Use at most this many champions"] = "最多使用不超过这个数量的勇士"
L["Use combat ally"] = "使用战斗盟友"
L["Use this slot"] = "使用这个空位"
L["Uses troops with the highest durability instead of the ones with the lowest"] = "使用最高生命值的部队，而不是最低的部队"
L["When no free followers are available shows empty follower"] = true
L["When we cant achieve the requested %1$s, we try to reach at least this one without (if possible) going over 100%%"] = true
L["Would start with "] = "将开始"
L["You are wasting |cffff0000%d|cffffd200 point(s)!!!"] = "你浪费了|cffff0000%d|cffffd200 点数!!!"
L[ [=[You need to close and restart World of Warcraft in order to update this version of OrderHallCommander.
Simply reloading UI is not enough]=] ] = true
L["You now need to press both %s and %s to start mission"] = true

return
end
L=l:NewLocale(me,"zhTW")
if (L) then
L["%1$d%% lower than %2$d%%. Lower %s"] = "%1$d%%低於%2$d%%，降低%s"
L["%s for a wowhead link popup"] = "%s跳出wowhead連結"
L["%s start the mission without even opening the mission page. No question asked"] = "按下 %s 一鍵派出任務。不用打開任務頁面，不做任何詢問。"
L["%s starts missions"] = "按下 %s 派出任務"
L["%s to actually start mission"] = "按下 %s 馬上派出任務"
L["%s to blacklist"] = "%s 加入忽略清單"
L["%s to remove from blacklist"] = "%s 從忽略清單移除"
L[ [=[%s, please review the tutorial
(Click the icon to dismiss this message and start the tutorial)]=] ] = [=[%s，請查看教學說明
(點擊圖示關閉這個訊息並且打開教學說明)]=]
L["%s, please review the tutorial\\n(Click the icon to dismiss this message)"] = "%s，請查看教學說明\\n(點擊圖示這個關閉訊息)"
L["Allow to start a mission directly from the mission list page (no single mission page shown)"] = "允許直接從任務列表頁面啟動任務（不會顯示個別任務頁面）"
L["Always counter increased resource cost"] = "總是反制增加資源花費"
L["Always counter increased time"] = "總是反制增加任務時間"
L["Always counter kill troops (ignored if we can only use troops with just 1 durability left)"] = "總是反制殺死部隊(如果我們用只剩一次耐久的部隊則忽略)"
L["Always counter no bonus loot threat"] = "總是反制沒有額外獎勵的威脅"
L["Artifact shown value is the base value without considering knowledge multiplier"] = "神兵顯示的值是基礎值，沒有經過神兵知識的加成。"
L["Attempting %s"] = "嘗試%s"
L["Base Chance"] = "基礎機率"
L["Better parties available in next future"] = "在將來有更好的隊伍"
L["Blacklisted"] = "已在忽略清單"
L["Blacklisted missions are ignored in Mission Control"] = "任務控制會忽略在忽略清單內的任務"
L["Bonus Chance"] = "額外獎勵機率"
L["Building Final report"] = "建立總結報告"
L["but using troops with just one durability left"] = "但使用只有一個耐久度的部隊"
L["Capped %1$s. Spend at least %2$d of them"] = "%1$s封頂了。花費至少%2$d在它身上"
L["Changes the sort order of missions in Mission panel"] = "改變任務面板上的任務排列順序"
L["Combat ally is proposed for missions so you can consider unassigning him"] = "戰鬥盟友被建議到任務，所以你可以考慮取消指派他"
L["Complete all missions without confirmation"] = "完成所有任務不須確認"
L["Configuration for mission party builder"] = "任務隊伍構建設置"
L["Cost reduced"] = "花費已降低"
L["Could not fulfill mission, aborting"] = "任務無法履行，忽略"
L["Counter kill Troops"] = "反制殺死部隊"
L["Customization options (non mission related)"] = "自定義選項（非任務相關）"
L["Disables warning: "] = "停用警告："
L["Dont use this slot"] = "不要使用這個空槽"
L["Don't use troops"] = "不要使用部隊"
L["Duration reduced"] = "持續時間已縮短"
L["Duration Time"] = "持續時間"
L["Elite: Prefer overcap"] = "精英: 寧願增加花費"
L["Elites mission mode"] = "精英任務模式"
L["Empty missions sorted as last"] = "空的任務排在最後"
L["Empty or 0% success mission are sorted as last. Does not apply to \"original\" method"] = "空的或成功率 0% 的任務排列在最後面。不要套用到  \"原始方法\"。"
L["Equipped by following champions:"] = "已裝備在下列勇士："
L["Expiration Time"] = "到期時間"
L["Favours leveling follower for xp missions"] = "傾向於使用升級中追隨者在經驗值任務"
L["For elite missions, tries hard to not go under 100% even at cost of overcapping"] = "對於精英任務，就算花費會增加，也別讓成功率低於 100%。"
L["General"] = "(G) 一般"
L["Global approx. xp reward"] = "整體大約經驗值獎勵"
L["Global approx. xp reward per hour"] = "每小時獲得整體經驗值獎勵"
L["HallComander Quick Mission Completion"] = "大廳任務快速完成"
L["If %1$s is lower than this, then we try to achieve at least %2$s without going over 100%%. Ignored for elite missions."] = "如果%1$s低於此值，那麼我們嘗試至少達到%2$s而不超過100%%。 忽視精英任務。"
L["If not checked, inactive followers are used as last chance"] = "不勾選時，閒置的追隨者會成為最後的考量。"
L[ [=[If you %s, you will lose them
Click on %s to abort]=] ] = [=[如果您繼續，您會失去它們
點擊%s來取消]=]
L["Ignore busy followers"] = "忽略任務中的追隨者"
L["Ignore inactive followers"] = "忽略閒置的追隨者"
L["Keep cost low"] = "保持低花費"
L["Keep extra bonus"] = "保持額外獎勵"
L["Keep time short"] = "保持短時間"
L["Keep time VERY short"] = "保持非常短的時間"
L[ [=[Launch the first filled mission with at least one locked follower.
Keep %s pressed to actually launch, a simple click will only print mission name with its followers list]=] ] = [=[至少使用一個鎖定的追隨者來出第一個任務。
按住 %s 會實際派出，點一下只會顯示任務名稱和和追隨者清單。]=]
L[ [=[Launch the first filled mission with at least one locked follower.
Keep SHIFT pressed to actually launch, a simple click will only print mission name with its followers list]=] ] = [=[至少使用一個鎖定的追隨者來出第一個任務。
按住 SHIFT 會實際派出，點一下只會顯示任務名稱和和追隨者清單。]=]
L["Level"] = "等級"
L["Lock all"] = "全部鎖定"
L["Lock this follower"] = "鎖定此追隨者"
L["Locked follower are only used in this mission"] = "鎖定只用於此任務的追隨者"
L["Make Order Hall Mission Panel movable"] = "讓大廳任務面板可移動"
L["Makes sure that no troops will be killed"] = "確保沒有部隊會被殺害"
L["Max champions"] = "最多勇士"
L["Maximize xp gain"] = "最大化經驗獲取"
L["Mission duration reduced"] = "任務時間已縮短"
L["Mission was capped due to total chance less than"] = "任務花費提高了，因為總成功率低於"
L["Missions"] = "(M) 任務"
L["Never kill Troops"] = "絕不殺死部隊"
L["No follower gained xp"] = "沒有追隨者獲得經驗"
L["No suitable missions. Have you reserved at least one follower?"] = "沒有合適的任務。 您是否至少保留一位追隨者？"
L["Not blacklisted"] = "不在忽略清單"
L["Nothing to report"] = "沒什麼可報告"
L["Notifies you when you have troops ready to be collected"] = "當部隊已準備好獲取時提醒你"
L["Only accept missions with time improved"] = "只允許有時間改善的任務"
L["Only consider elite missions"] = "只考慮精英任務"
L["Only need %s instead of %s to start a mission from mission list"] = "要從任務清單派出任務，只需要 %s 而不是 %s。"
L["Only use champions even if troops are available"] = "有可用的部隊時，仍然只要使用勇士。"
L["Open configuration"] = "開啟設置選項"
L[ [=[OrderHallCommander overrides GarrisonCommander for Order Hall Management.
 You can revert to GarrisonCommander simply disabling OrderhallCommander.
If instead you like OrderHallCommander remember to add it to Curse client and keep it updated]=] ] = [=[職業大廳指揮官已經取代要塞指揮官來管理職業大廳。
要返回使用要塞指揮官，只要停用職業大廳指揮官插件就可以了。]=]
L["Original method"] = "原始方式"
L["Position is not saved on logout"] = "位置不會在登出後儲存"
L["Prefer high durability"] = "喜好高耐久度"
L["Quick start first mission"] = "快速開始第一個任務"
L["Remove no champions warning"] = "移除缺少勇士警告"
L["Restart tutorial from beginning"] = "從開始的地方重啟指南"
L["Resume tutorial"] = "繼續指南"
L["Resurrect troops effect"] = "復活部隊效果"
L["Reward type"] = "獎勵類型"
L["Sets all switches to a very permissive setup. Very similar to 1.4.4"] = "所有設定都更改為非常寬鬆的設定，和 1.44 版非常相似。"
L["Show tutorial"] = "顯示指南"
L["Show/hide OrderHallCommander mission menu"] = "顯示/隱藏大廳指揮官任務選單"
L["Sort missions by:"] = "任務排序依據："
L["Started with "] = "已經派出 "
L["Success Chance"] = "成功機率"
L["Troop ready alert"] = "部隊整備提醒"
L["Unable to fill missions, raise \"%s\""] = "無法指派任務，請提升 \"%s\""
L["Unable to fill missions. Check your switches"] = "無法分派任務，請檢查你的設定選項。"
L["Unable to start mission, aborting"] = "無法開始任務，中止"
L["Unlock all"] = "全部解除鎖定"
L["Unlock this follower"] = "解鎖此追隨者"
L["Unlocks all follower and slots at once"] = "一次解鎖所有追隨者和空槽"
L["Unsafe mission start"] = "不安全的一鍵派出"
L["Upgrading to |cff00ff00%d|r"] = "升級到|cff00ff00%d|r"
L["URL Copy"] = "複製網址"
L["Use at most this many champions"] = "至少使用這個數量的勇士"
L["Use combat ally"] = "使用戰鬥盟友"
L["Use this slot"] = "使用此空槽"
L["Uses troops with the highest durability instead of the ones with the lowest"] = "使用最高耐久性的部隊，而不是最低的部隊"
L["When no free followers are available shows empty follower"] = "沒有可用的追隨者時，顯示空欄位。"
L["When we cant achieve the requested %1$s, we try to reach at least this one without (if possible) going over 100%%"] = "當我們無法實現請求的%1$s時, 我們嘗試至少達到這一目標, 而不 (如果可能) 超過100%%"
L["Would start with "] = "將會派出 "
L["You are wasting |cffff0000%d|cffffd200 point(s)!!!"] = "你浪費了|cffff0000%d|cffffd200 點數!!!"
L[ [=[You need to close and restart World of Warcraft in order to update this version of OrderHallCommander.
Simply reloading UI is not enough]=] ] = [=[您需要關閉並重新啟動魔獸世界才能更新此版本的OrderHallCommander。
簡單的重新載入UI是不夠的]=]
L["You now need to press both %s and %s to start mission"] = "您現在需要同時按下%s和%s來啟動任務"
L["ChampionComander Quick Mission Completion"] = "快速完成任務"

return
end
